name: Create_Docker_Image

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install  
      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - name: Docker build
        run: docker build . --file Dockerfile --tag $DOCKER_USER/hellodocker:${{ steps.date.outputs.date }}
      - name: Docker push
        run: docker push $DOCKER_USER/hellodocker:${{ steps.date.outputs.date }}